# Generated by Django 4.2.17 on 2026-09-14 20:31

import core.models.assertion
import core.models.taxonomy
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("facility", "Facility"),
                            ("asset", "Asset"),
                            ("person", "Person"),
                            ("document_node", "Document"),
                            ("event", "Event"),
                            ("program", "Program"),
                        ],
                        max_length=30,
                    ),
                ),
                ("canonical_name", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("merged", "Merged"),
                            ("disputed", "Disputed"),
                            ("stub", "Stub"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "redirects_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redirected_from",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "db_table": "entity",
            },
        ),
        migrations.CreateModel(
            name="ExtractionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task", models.CharField(max_length=100)),
                ("prompt_sha256", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=100)),
                ("code_version", models.CharField(max_length=40)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("stats", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "extraction_run",
            },
        ),
        migrations.CreateModel(
            name="PredicateDef",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "predicate_def",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("regulator", "Regulator"),
                            ("primary", "Primary"),
                            ("trade_press", "Trade Press"),
                            ("aggregator", "Aggregator"),
                            ("social", "Social"),
                            ("llm", "LLM"),
                            ("external_contributor", "External Contributor"),
                        ],
                        max_length=30,
                    ),
                ),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("base_trust", models.SmallIntegerField(default=50)),
                ("robots_policy", models.TextField(blank=True, null=True)),
                ("license_note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "source",
            },
        ),
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("version", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "taxonomy",
                "unique_together": {("key", "version")},
            },
        ),
        migrations.CreateModel(
            name="TaxonomyNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("label", models.CharField(max_length=255)),
                ("definition", models.TextField()),
                ("examples", models.JSONField(blank=True, default=list)),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="core.taxonomy",
                    ),
                ),
            ],
            options={
                "db_table": "taxonomy_node",
                "unique_together": {("taxonomy", "path")},
            },
        ),
        migrations.CreateModel(
            name="EntityMerge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merged_at", models.DateTimeField(auto_now_add=True)),
                ("performed_by", models.CharField(max_length=255)),
                ("rationale", models.JSONField()),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merges_kept",
                        to="core.entity",
                    ),
                ),
                (
                    "merged",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merges_merged",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "db_table": "entity_merge",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.TextField(blank=True, null=True)),
                ("content_sha256", models.CharField(max_length=64, unique=True)),
                ("storage_key", models.TextField()),
                ("media_type", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("lang", models.CharField(blank=True, max_length=2, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("text_content", models.TextField(blank=True, null=True)),
                ("trust_override", models.SmallIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="core.source",
                    ),
                ),
            ],
            options={
                "db_table": "document",
            },
        ),
        migrations.CreateModel(
            name="Conflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute_key", models.CharField(max_length=100)),
                (
                    "assertion_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(), size=None
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("picked", "Picked one"),
                            ("range", "Used range"),
                            ("both_wrong", "Both wrong"),
                            ("pending", "Pending"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "resolved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "db_table": "conflict",
            },
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=3, default=1.0, max_digits=4),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "valid_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default=core.models.taxonomy._open_range
                    ),
                ),
                ("confidence", models.SmallIntegerField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("extracted", "Extracted"),
                            ("manual", "Manual"),
                            ("derived", "Derived"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.document",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="core.entity",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classifications",
                        to="core.taxonomynode",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.extractionrun",
                    ),
                ),
            ],
            options={
                "db_table": "classification",
            },
        ),
        migrations.CreateModel(
            name="AttributeDef",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("entity_type", models.CharField(max_length=30)),
                ("label", models.CharField(max_length=255)),
                (
                    "datatype",
                    models.CharField(
                        choices=[
                            ("int", "Integer"),
                            ("decimal", "Decimal"),
                            ("text", "Text"),
                            ("date", "Date"),
                            ("bool", "Boolean"),
                            ("money", "Money"),
                            ("geo", "Geographic"),
                            ("enum", "Enum"),
                            ("taxonomy_ref", "Taxonomy Reference"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cardinality",
                    models.CharField(
                        choices=[("single", "Single"), ("multi", "Multi")],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("is_projected", models.BooleanField(default=True)),
                ("is_promoted", models.BooleanField(default=False)),
                ("volatility_days", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "taxonomy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.taxonomy",
                    ),
                ),
            ],
            options={
                "db_table": "attribute_def",
            },
        ),
        migrations.CreateModel(
            name="Assertion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "value_num",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "value_low",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                (
                    "value_high",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                (
                    "valid_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default=core.models.assertion._open_range
                    ),
                ),
                ("observed_at", models.DateTimeField(auto_now_add=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("quote", models.TextField(blank=True, null=True)),
                ("char_start", models.IntegerField(blank=True, null=True)),
                ("char_end", models.IntegerField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("extracted", "Extracted"),
                            ("structured_api", "Structured API"),
                            ("manual", "Manual"),
                            ("derived", "Derived"),
                            ("imputed", "Imputed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "derived_from",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("confidence", models.SmallIntegerField()),
                (
                    "confidence_model_version",
                    models.CharField(default="v1", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("candidate", "Candidate"),
                            ("rejected", "Rejected"),
                            ("conflicted", "Conflicted"),
                        ],
                        default="accepted",
                        max_length=20,
                    ),
                ),
                (
                    "review_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("corrected", "Corrected"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        db_column="attribute_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.attributedef",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assertions",
                        to="core.document",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assertions",
                        to="core.entity",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assertions",
                        to="core.extractionrun",
                    ),
                ),
                (
                    "value_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referenced_in_assertions",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "db_table": "assertion",
            },
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualifiers", models.JSONField(default=dict)),
                (
                    "valid_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default=core.models.assertion._open_range
                    ),
                ),
                ("observed_at", models.DateTimeField(auto_now_add=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("quote", models.TextField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("extracted", "Extracted"),
                            ("structured_api", "Structured API"),
                            ("manual", "Manual"),
                            ("derived", "Derived"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.SmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("candidate", "Candidate"),
                            ("rejected", "Rejected"),
                        ],
                        default="accepted",
                        max_length=20,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.document",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_relations",
                        to="core.entity",
                    ),
                ),
                (
                    "predicate",
                    models.ForeignKey(
                        db_column="predicate",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.predicatedef",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.extractionrun",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_relations",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "db_table": "relation",
                "indexes": [
                    models.Index(
                        condition=models.Q(("superseded_at__isnull", True)),
                        fields=["subject", "predicate"],
                        name="relation_subject_idx",
                    ),
                    models.Index(
                        condition=models.Q(("superseded_at__isnull", True)),
                        fields=["object", "predicate"],
                        name="relation_object_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            ("wikidata", "Wikidata QID"),
                            ("lei", "LEI"),
                            ("cik", "SEC CIK"),
                            ("duns", "DUNS"),
                            ("domain", "Domain"),
                            ("norad", "NORAD ID"),
                            ("cospar", "COSPAR ID"),
                            ("ror", "ROR"),
                            ("crunchbase", "Crunchbase"),
                            ("isni", "ISNI"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("confidence", models.SmallIntegerField(default=100)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.document",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "db_table": "entity_identifier",
                "unique_together": {("scheme", "value")},
            },
        ),
        migrations.CreateModel(
            name="EntityAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=500)),
                ("alias_norm", models.CharField(max_length=500)),
                (
                    "alias_kind",
                    models.CharField(
                        choices=[
                            ("legal", "Legal Name"),
                            ("trading", "Trading Name"),
                            ("former", "Former Name"),
                            ("ticker", "Ticker"),
                            ("abbrev", "Abbreviation"),
                            ("misspelling", "Misspelling"),
                            ("translit", "Transliteration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lang", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "valid_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        blank=True, null=True
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.document",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "db_table": "entity_alias",
                "indexes": [
                    models.Index(
                        fields=["alias_norm"], name="entity_alia_alias_n_4cc8a0_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["entity_type", "status"], name="entity_entity__b1cc9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["source", "-published_at"], name="document_source__fbd39b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assertion",
            index=models.Index(
                condition=models.Q(("superseded_at__isnull", True)),
                fields=["entity", "attribute", "status"],
                name="assertion_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assertion",
            index=models.Index(
                fields=["document"], name="assertion_documen_11c1a2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assertion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("method", "extracted"), _negated=True),
                    models.Q(("document__isnull", False), ("quote__isnull", False)),
                    _connector="OR",
                ),
                name="extracted_needs_source",
            ),
        ),
    ]
