# Generated by Django 4.2.17 on 2026-09-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_postgres_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="pipeline_status",
            field=models.CharField(
                choices=[
                    ("fetched", "Fetched"),
                    ("parsed", "Parsed"),
                    ("triaged", "Triaged"),
                    ("skipped", "Skipped"),
                    ("extracted", "Extracted"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="fetched",
                max_length=20,
            ),
        ),
    ]
