# Generated by Django 4.2.17 on 2026-09-14 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_entity_current_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="watchlist",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="entity",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("merged", "Merged"),
                    ("disputed", "Disputed"),
                    ("stub", "Stub"),
                    ("dormant", "Dormant"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ScheduledSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_url", models.TextField()),
                (
                    "feed_type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS/Atom Feed"),
                            ("sitemap", "Sitemap"),
                            ("manual", "Single URL"),
                        ],
                        default="rss",
                        max_length=20,
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("event_driven", "Event-driven"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "entity_hint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_sources",
                        to="core.entity",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_sources",
                        to="core.source",
                    ),
                ),
            ],
            options={
                "db_table": "scheduled_source",
            },
        ),
        migrations.CreateModel(
            name="LLMCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        choices=[
                            ("triage", "Triage"),
                            ("extract", "Extract"),
                            ("resolve", "Resolve"),
                            ("analysis", "Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("tokens_in", models.IntegerField()),
                ("tokens_out", models.IntegerField()),
                ("cost_usd", models.DecimalField(decimal_places=6, max_digits=10)),
                ("called_at", models.DateTimeField(auto_now_add=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_calls",
                        to="core.entity",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_calls",
                        to="core.extractionrun",
                    ),
                ),
            ],
            options={
                "db_table": "llm_call",
                "indexes": [
                    models.Index(
                        fields=["called_at"], name="llm_call_called__a1e813_idx"
                    ),
                    models.Index(
                        fields=["entity", "called_at"],
                        name="llm_call_entity__3b9dd6_idx",
                    ),
                ],
            },
        ),
    ]
