# Generated by Django 4.2.17 on 2026-10-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_entity_current_staleness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitysummary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='knowledgefragment',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('financial', 'Financial'), ('competitive', 'Competitive'), ('regulatory', 'Regulatory'), ('strategic', 'Strategic'), ('operational', 'Operational'), ('people', 'People'), ('challenge', 'Challenge'), ('research', 'Research & Publications')], max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgefragment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
