from django.urls import path
from curation import views

app_name = 'curation'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('auto-news/', views.auto_news, name='auto_news'),
    path('company-research/', views.company_research, name='company_research'),
    path('question-research/', views.question_research, name='question_research'),
    path('stop/', views.stop_all_tasks, name='stop_all'),
    path('resume/', views.resume_tasks, name='resume_tasks'),
    path('ingest/', views.ingest_trigger, name='ingest_trigger'),
    path('stubs/', views.stubs, name='stubs'),
    path('stubs/<uuid:entity_id>/promote/', views.promote_stub, name='promote_stub'),
    path('candidates/', views.candidates, name='candidates'),
    path('candidates/<int:assertion_id>/review/', views.review_assertion, name='review_assertion'),
    path('entity/<uuid:entity_id>/', views.entity_profile, name='entity_profile'),
    path('connections/', views.connections, name='connections'),
    path('research/', views.research, name='research'),
    path('insights/', views.insights, name='insights'),
    path('funding/', views.funding, name='funding'),
    path('taxonomy/', views.taxonomy, name='taxonomy'),
    path('taxonomy/proposals/', views.taxonomy_proposals, name='taxonomy_proposals'),
    path('taxonomy/evolve/', views.run_evolve_taxonomy, name='run_evolve_taxonomy'),
    path('prompts/', views.prompts_list, name='prompts_list'),
    path('prompts/<str:key>/edit/', views.prompt_edit, name='prompt_edit'),
    path('research-all/', views.research_all, name='research_all'),
    path('summarise-all/', views.summarise_all, name='summarise_all'),
    path('classify-all/', views.classify_all, name='classify_all'),
    path('assess-all/', views.assess_all, name='assess_all'),
    path('fill-locations/', views.fill_locations_all, name='fill_locations_all'),
    path('fill-addresses/', views.fill_addresses_all, name='fill_addresses_all'),
    path('geocode-offices/', views.geocode_offices, name='geocode_offices'),
    path('merge-geo-duplicates/', views.merge_geography_duplicates, name='merge_geography_duplicates'),
    path('dedup/', views.run_dedup_sweep, name='run_dedup_sweep'),
    path('map/', views.map_view, name='map'),
    path('map/data/', views.map_data, name='map_data'),
    path('search/', views.entity_search, name='entity_search'),
]
